version: '2'
services:
  nginx:
    image: nginx:1.11.13
    container_name: Nginx
    ports:
      - "8001:8001"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./flags:/usr/share/nginx/html/flags"
      - "./nginx_logs:/var/log/nginx/"
      - "./nginx.nginx:/etc/nginx/conf.d/default.conf"
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
  vaurien-delay:
    image: registry.cn-beijing.aliyuncs.com/korewayume/flags-server-vaurien
    container_name: Vaurien-DELAY
    links:
      - "nginx:nginx"
    ports:
      - "8002:8002"
    command: ./vaurien_delay.sh
  vaurien-error:
    image: registry.cn-beijing.aliyuncs.com/korewayume/flags-server-vaurien
    container_name: Vaurien-ERROR
    links:
      - "nginx:nginx"
    ports:
      - "8003:8003"
    command: ./vaurien_error_delay.sh
